name: stock-sentiment

services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: stock-sentiment-proxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8080:8080"
      - "9901:9901"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9901/ready"]
      interval: 5s
      timeout: 2s
      retries: 3

networks:
  proxy-network: